name: test.yml
on: [push]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "22.x"
      - name: dependencies install
        run: yarn install
